### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by arthurvr** [RichardLitt/awesome-fantasy#10]
This repo seems to miss a license :wink:

Ref https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license

**Comment by RichardLitt** [comment]
@arthurvr Are you just going around to every list asking for a license?

**Comment by arthurvr** [comment]
@RichardLitt No, not really. Other things too. Just generally trying to get some lists cleaned up. See https://github.com/sindresorhus/awesome/issues/207.

**Comment by RichardLitt** [comment]
Fair enough.
