### ISSUE TITLE
Question re: genres

### ISSUE THREAD

**Issue by nahkampf** [RichardLitt/awesome-fantasy#162]
Hi! Will add Richard Morgans A Land Fit for Heroes-trilogy, but am wondering exactly how this list classifies "epic" vs "standard"? ALFFH has elements that I guess one would call epic (there's actual gods involved, for instance) but the "action" is pretty (for a fantasy trilogy) low key and non-epic.

**Comment by RichardLitt** [comment]
No idea. Choose what makes more sense for you. :)

**Comment by billyboy4** [comment]
Are you the big din that's been fucking Teresa hollamby behind my back
