### ISSUE TITLE
Graphic Novels

### ISSUE THREAD

**Issue by SeanSWatkins** [RichardLitt/awesome-fantasy#18]
This isn't really an issue, just a question.

I am currently reading the first Sandman graphic novel, would like to add it to the list as soon as I am done. 

Should I create a graphic novel section? or just add it to Horror (Which i think it is classfied as)?

**Comment by RichardLitt** [comment]
Oh! Good question!

Make a graphic novel section. Sandman is fracking awesome. I wouldn't count it as horror.

**Comment by SeanSWatkins** [comment]
Yeah, really enjoying it. Don't find it creepy in the least...I am a bit damaged though, which could explain why. lol.

Cool, will do :+1:

**Comment by RichardLitt** [comment]
You're a whole human, just like the rest of us. Enjoy what you enjoy.
