### ISSUE TITLE
Add "The Deed of Paksenarrion"?

### ISSUE THREAD

**Issue by samueljseay** [RichardLitt/awesome-fantasy#20]
Hi,

I hope its ok to suggest a series in an issue like this, I couldn't recommend "The Deed of Paksenarrion" highly enough and I think it totally deserves a spot in this list. https://www.goodreads.com/book/show/96281.The_Deed_of_Paksenarrion

Thanks by the way for writing this list, I discovered Gene Wolfe via this list! In New Zealand it seems Gene Wolfe is not on anyone's radar for some reason (probably because the LOTR movies were made here :stuck_out_tongue: )

**Comment by RichardLitt** [comment]
@samueljseay Totally OK to recommend in an issue. Do you not want to add it to the file yourself? 

Oh man, if you found Gene Wolfe because of this, than I am glad I made this. He's the best.

**Comment by samueljseay** [comment]
Hopefully I can get around to adding it myself yep, I can't say I'm very good at writing reviews but I'll give it a crack :)

**Comment by samueljseay** [comment]
#21
