### ISSUE TITLE
Match current standards for awesome-lists as defined by @sindresorhus

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/awesome-fantasy#24]
@sindresorhus has changed the standards for an awesome-list, and this list needs to be changed to match. See https://github.com/sindresorhus/awesome/issues/926 for more. 

## Criteria
- [x] **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
- [x] It's the result of hard work and the best I could possibly produce.
- [x] Non-generated Markdown file in a GitHub repo.
- [x] The repo should have the following [GitHub topics](https://help.github.com/articles/about-topics) set: `awesome-list`, `awesome`, `list`. I encourage you to add more relevant topics.
- [x] Not a duplicate.
- [x] Includes a succinct description of the project/theme at the top of the readme. [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
- [x] Includes a project logo/illustration whenever possible.
	- [x] Placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
	- [x] The image should link to the project website or any relevant website.
	- [x] The image should be high-DPI. Set it to maximum half the width of the original image.
- [x] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x] Has the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
- [x] Has a Table of Contents section.
	- [x] Should be named `Contents`, not `Table of Contents`.
	- [x] Should be the first section in the list.
- [x] Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
	- [x] That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
	- [x] If you use a license badge, it should be SVG, not PNG.
- [x] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
	- [x] The file should be named `contributing.md`. Casing is up to you.
- [x] Has consistent formatting and proper spelling/grammar.
	- [ ] Each link description starts with an uppercase character and ends with a period.<br>Example: `- [AVA](…) - JavaScript test runner.`
	- [ ] Drop all the `A` / `An` prefixes in the descriptions.
	- [x] Consistent naming. For example, `Node.js`, not `NodeJS` or `node.js`.
- [x] Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.

**Comment by RichardLitt** [comment]
I believe this is appropriate. I do not want to use the Example link descriptions, as this repo works a bit differently. If someone has an issue with this, reopen.

**Comment by sindresorhus** [comment]
> If you use a license badge, it should be SVG, not PNG.

This is not done. It should be SVG. See the badge in the main Awesome list.

> I do not want to use the Example link descriptions, as this repo works a bit differently.

That's totally fine. It's guidelines. In this case I agree the current format works much better.

**Comment by RichardLitt** [comment]
You're right! Good catch. Thank you. Fixed. 

> That's totally fine. It's guidelines. In this case I agree the current format works much better.

Great. :)
