### ISSUE TITLE
Unreleased Works

### ISSUE THREAD

**Issue by SeanSWatkins** [RichardLitt/awesome-fantasy#25]
Would it be cool to add unreleased works?

E.g.  Pat Rothfuss' Doors Of Stone, and Brandon Sandersons Oathbringer novels?

I'll add a PR for them in the meantime, let me know if you don't want to and would rather wait till they are released

**Comment by RichardLitt** [comment]
Interesting idea, but I don't think we should do that. They're not awesome, as they do not exist. Holding them up as awesome is also unfair to the authors. :)

**Comment by SeanSWatkins** [comment]
Ah, that is a good point.
