### ISSUE TITLE
Establish standard for book series links

### ISSUE THREAD

**Issue by jybaran** [RichardLitt/awesome-fantasy#32]
At the moment it seems like some book series have a link to the Goodreads series page while others have a link to the Wikipedia series page.

**Comment by RichardLitt** [comment]
Either one works for me. Frankly, I prefer Wikipedia to Goodreads (never been the biggest fan of Goodreads). 

Is there a problem with either or?

**Comment by jybaran** [comment]
(I also generally prefer Wikipedia)

Might be nice to say one or the other in the contribution guidelines, just for the sake of having a policy on it, and for consistency?

**Comment by sjelfull** [comment]
I haven't got anything substantial to go on, but I think the quality between the two sites varies. Sometimes Wikipedia has better coverage on a series, and sometimes Goodreads is the best (even though the site itself is bad in many ways).

I personally think either is fine.

**Comment by RichardLitt** [comment]
I agree with @sjelfull. 

How about we add a note saying: "Either is fine, choose the one with the better coverage." Does that work for your consistency needs, @jybaran?
